### PR TITLE
Moved from pulseio.PWMOut to pwmio.PWMOut

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Comment by dherrada** [comment]
@tannewt Should this repo get actions?

**Comment by brentru** [comment]
Related to https://github.com/adafruit/METROX-CircuitPython/issues/5

@dherrada  So, we haven't done MetroX for CircuitPython..yet. This library contains code written a long time ago while the CircuitPython API was still being worked on. I'm not sure this repo should get actions, or if we should just archive it and add a note...

@ladyada  do you agree with archiving this repo for now, until we're ready to un-archive it?

**Comment by dherrada** [comment]
@brentru Sounds good.

**Comment by ladyada** [comment]
yep thats ok!

**Comment by brentru** [comment]
Ok, will close out issues/PRs/update and archive for now.

**Comment by tannewt** [comment]
@brentru are you going to update the code?

**Comment by brentru** [comment]
@tannewt  The code within _this_ PR?

**Comment by brentru** [comment]
@ladyada  On topic of archiving this repo - TravisCI (https://travis-ci.com/github/adafruit/METROX-CircuitPython/) could be turned off for this repo. When we start metrox circuitpython again, we'll switch to actions per #5

**Comment by tannewt** [comment]
Ya, that and I think you moved it to Learn too.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
